<div  class ="row">
    <div  class = "col-sm-12">
    <h2> Lista de categorías </h2>
         <div class ="btn-group pull-left">
       <a href="<?php echo APP_URL."categorias/agregar"; ?>" >
            <button type="button" class="btn btn-primary add">
                <span class="glyphicon glyphicon-plus"></span> Categorias
            </button>
</a>
</div>
    <div class="btn-group pull-right">
    <a href="<?php echo APP_URL."tareas/agregar"; ?>" >
            <button type="button" class="btn btn-primary add">
                <span class="glyphicon glyphicon-plus"></span> Tarea
            </button>
</a >
</div >
<br > <br >
        <div class="table-responsive">
        <table class="table-hover table-bordered table-condensed">
                <tr>
                    <th> ID </th>
                    <th> Nombre </th>
                    <th> Acción </th>
                </tr>
<?php foreach ($this->categorias as $categoria): ?>   
     <tr>
         <td><?php echo $categoria["id"]; ?> </td>  
         <td><?php echo $categoria["nombre"]; ?> </td>  
         <td><a href="<?php echo APP_URL."categorias/editar/".$categoria["id"]; ?>" > 
         <span class="glyphicon glyphicon-edit"></span></a>
        <a href="<?php echo APP_URL."categorias/eliminar/".$categoria["id"]; ?>" class="confirmation"> 
        <span class="glyphicon glyphicon-basura"></span></a>
    </tr>
                <?php endforeach; ?> 
            </table >
        </div>
  